spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_SCHEMA}?currentSchema=hostsmanager
    username: root
    password: 12345
  #    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type: TRACE

security:
  jwt:
    secret: ioyur239874
    ttl: 259200000 # three days in ms

#zabbix:
#  url: http://192.168.0.207:8081/zabbix/api_jsonrpc.php
#  login: api
#  password: 123

hostsmanager:
  search:
    mode: "sonic" # none | sonic
    sonic:
      address: ${SONIC_ADDRESS}
      port: ${SONIC_PORT}
      timeout: ${SONIC_TIMEOUT}
      password: ${SONIC_PASSWORD}
  service-info:
    admin-email: ${ADMIN_EMAIL}
    location: ${SERVICE_LOCATION}
    description: ${SERVICE_DESCRIPTION}