spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hostsmanager
    username: root
    password: 12345
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type: TRACE

security:
  jwt:
    secret: ioyur239874
    ttl: 259200000 # three days in ms

#zabbix:
#  url: http://192.168.0.207:8081/zabbix/api_jsonrpc.php
#  login: api
#  password: 123

hostsmanager:
  service-info:
    admin-email: ${ADMIN_EMAIL}
    location: ${SERVICE_LOCATION}
    description: ${SERVICE_DESCRIPTION}