version: "3.9"
services:
  hostsmanager:
    build: ..
    ports:
      - 8080:8080
    volumes:
      - ./application.yml:/root/application.yml
    depends_on:
      - mysql
      - flyway
    environment:
      ADMIN_EMAIL: "someone@somewhere.com"
      SERVICE_LOCATION: "Somewhere"
      SERVICE_DESCRIPTION: ""

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=hostsmanager -user=root -password=12345 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: hostsmanager
    volumes:
      - /location/to/datadir:/var/lib/mysql