version: "3.9"
services:
  hostsmanager:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - ${BACKEND_HTTP_PORT}:8080
    volumes:
      - ./application.yml:/root/application.yml
    depends_on:
      - mysql
      - flyway
    restart: always
    environment:
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SERVICE_LOCATION: ${SERVICE_LOCATION}
      SERVICE_DESCRIPTION: ${SERVICE_DESCRIPTION}

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=${MYSQL_SCHEMA} -user=root -password=12345 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_SCHEMA}
    volumes:
      - ${MYSQL_DATADIR}:/var/lib/mysql