#include remote debug at port 8000 & forward database port 3306
version: "3.9"
services:
  hostsmanager:
    environment:
      JAVA_OPTS: ""
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - 8000:8000

  postgres:
    ports:
      - 5432:5432

  sonic:
    ports:
      - 1491:1491

  pgadmin:
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - 5050:80
    depends_on:
      postgres:
        condition: service_healthy