version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0.2
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ./hostmanager-backend
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          working_directory: ./hostmanager-backend
          command: mvn test

workflows:
  buildAndTest:
    jobs:
      - build-and-test