spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hostsmanager
    username: root
    password: 12345
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type: TRACE
server:
  port: 8081
security:
  jwt:
    secret: ioyur239874
    ttl: 259200000 # three days in ms

#zabbix:
#  url: http://192.168.0.207:8081/zabbix/api_jsonrpc.php
#  login: api
#  password: 123

hostsmanager:
  search:
    mode: "sonic" # none | sonic
    sonic:
      address: "localhost"
      port: 14910
      timeout: 20000
      password: "SecretPassword"
  service-info:
    admin-email: someone@somewhere.com
    location: Test instance
    description: Test instance of hostsmanager in there