spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hm_test2
    username: root
    password: 123
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE