spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hm_test2
    username: root
    password: 123
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type: TRACE

security:
  jwt:
    secret: ioyur239874
    ttl: 259200000 # three days in ms

zabbix:
  url: http://192.168.0.207:8081/zabbix/api_jsonrpc.php
  login: api
  password: 123