spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hm_test2
    username: root
    password: ***REMOVED***
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

security:
  jwt:
    secret: ioyur239874
    ttl: 999999